### ISSUE TITLE
Wheels lack the proj-datumgrid-1.8 package

### ISSUE THREAD

**Issue by rouault** [sgillies/rasterio-wheels#33]
Was brought to my attention today by a user which used the rasterio-wheels that he got incorrect results when reprojecting a dataset from NAD27 to WGS84, when comparing to the result they got with a non-wheel installation or plain gdalwarp. As far as I can see in https://github.com/rasterio/rasterio-wheels/blob/master/config.sh, only PROJ is built, but the https://download.osgeo.org/proj/proj-datumgrid-1.8.zip support data, that contains the "conus" grid for NAD27->NAD83/WGS84, is not unzipped in /usr/share/proj.

**Comment by daniviga** [comment]
Thanks @rouault for the support you provided us (via @mbernasocchi). We confirm that adding the extra datum grids fixed our GDAL wheel (see https://github.com/gem/oq-builders/pull/128) when warping NAD27 rasters.

Just a note: since it's a wheel the datum data should not be added to `/usr/share/proj` but to  `osgeo/proj_data` inside the `whl` (as in the PR mentioned above). Thank you!

**Comment by sgillies** [comment]
On it. Was looking for a reason to build an entirely new set of wheels :)

I'm going to ask on the rasterio discussion group if people think it's worth inflating the wheels by an extra 6+ MB.

**Comment by rouault** [comment]
> it's worth inflating the wheels by an extra 6+ MB.

Well that's just a tiny subset of the 1.4 GB we have now... :-) Seems https://github.com/rouault/PROJ/blob/rfc4_remote_and_geotiff_grid/docs/source/community/rfc/rfc-4.rst has some potential :-)

**Comment by sgillies** [comment]
I haven't heard any rasterio users object to an extra 6 MB, so I'm going to do it.
